### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by manotejmeka** [manotejmeka/MI-449-SS17-741-js-create-an-api-with-express-URJy-_#1]
## Create a todo list API

@stuartpearman Can you take a look at this? It's [hosted here](https://mekamano-khxn-8th0o_1eurjy-_.herokuapp.com/) and meets the following criteria:

- [x] Todos should have a field for the todo text and one to indicate whether or not the task has been completed
- [x] User should be able to see all todo items at `/todos`
- [x] POSTing to `/todos` should create a new todo item
- [x] Should be able to `GET`, `PUT`, and `DELETE` to `/todos/:id`
- [x] URLs besides `/todos` and `/todos/:id` respond with a 404 status code
- [x] If a specific todo at `/todos/:id` does not exist, a 404 status code should be returned
- [x] All requests and responses should be in JSON format
- [x] Should have a `.gitignore` file to keep unwanted files and folders from being tracked by git

The project is not finished fully. I am having some problems and I am pushing code to show you what I have. I am having some problems with the postman software and how to debug it

**Comment by manotejmeka** [comment]
https://mekamano-khxn-8th0o-1eurjy-.herokuapp.com/ That is is link to my heroku the underlines has some problems

**Comment by stuartpearman** [comment]
Hi Manotej, your 404's don't seem to be working. Your `todos/:id` route seems to have a duplicate, and your main 404 still needs to be made as far as I can tell.

Let me know when you've made changes 😎

**Comment by stuartpearman** [comment]
Also, your `POST` request times out, and the `PUT` request redirects to a unknown path.

**Comment by manotejmeka** [comment]
@stuartpearman Everything should be fixed now

**Comment by stuartpearman** [comment]
Hi Manotej, your API still doesn't handle _all_ unknown paths. If I try `GET /kjadnlkdjfnas`, I should also get a 404 response. Check the 404 slide of the lesson for details.

**Comment by manotejmeka** [comment]
@stuartpearman I had that code in, but I think I must have forgotten to push the code. Sorry

**Comment by stuartpearman** [comment]
Sweet. Congrats Manotej, you're done! :shipit:

It's been awesome having you in class sir. You're a great developer and Microsoft is lucky to have you. Enjoy the summer 🌞
